default: &default
  adapter: postgresql
  encoding: unicode
  # database: <%= ENV['DATABASE_NAME'] %>
  # username: <%= ENV['DATABASE_USER'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  # port: <%= ENV['DATABASE_PORT'] || '5432' %>
  # host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: pagcom_bank_development
  username: guilhermereis

test:
  <<: *default

production:
  <<: *default
